SELECT
    SUM(CASE WHEN au_id='A01' THEN 1 ELSE 0 END) AS A01,
    SUM(CASE WHEN au_id='A02' THEN 1 ELSE 0 END) AS A02,
    SUM(CASE WHEN au_id='A03' THEN 1 ELSE 0 END) AS A03,
    SUM(CASE WHEN au_id='A04' THEN 1 ELSE 0 END) AS A04,
    SUM(CASE WHEN au_id='A05' THEN 1 ELSE 0 END) AS A05,
    SUM(CASE WHEN au_id='A06' THEN 1 ELSE 0 END) AS A06,
    SUM(CASE WHEN au_id='A07' THEN 1 ELSE 0 END) AS A07
  FROM title_authors;