('push', 'argument', '0')
('push', 'constant', '2')
('lt',)
('push', 'argument', '0')
('push', 'argument', '0')
('push', 'constant', '2')
('sub',)
('push', 'argument', '0')
('push', 'constant', '1')
('sub',)
('add',)
