<?php
include_once "header.php";
echo "<body>";

$cellwidtd=30;
$cellheight=30;
$emptysea="<img border=0 src='ocean.jpg' widtd='".$cellwidtd."' height='".$cellheight."'>";

echo "<form metdod='post'>";	
echo "<table border=1>";
	echo "<tr>";
	echo "<th></th><th>A</th><th>B</th><th>C</th><th>D</th><th>E</th><th>F</th><th>G</th><th>H</th><th>I</th><th>J</th>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>1</th>";
		echo "<td><input type='submit' name='subA1' value='A1'/></td>";
		echo "<td><input type='submit' name='subB1' value='B1'/></td>";
		echo "<td><input type='submit' name='subC1' value='C1'/></td>";
		echo "<td><input type='submit' name='subD1' value='D1'/></td>";
		echo "<td><input type='submit' name='subE1' value='E1'/></td>";
		echo "<td><input type='submit' name='subF1' value='F1'/></td>";
		echo "<td><input type='submit' name='subG1' value='G1'/></td>";
		echo "<td><input type='submit' name='subH1' value='H1'/></td>";
		echo "<td><input type='submit' name='subI1' value='I1'/></td>";
		echo "<td><input type='submit' name='subJ1' value='J1'/></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>2</th>";
		echo "<td><input type='submit' name='subA2' value='A2'/></td>";
		echo "<td><input type='submit' name='subB2' value='B2'/></td>";
		echo "<td><input type='submit' name='subC2' value='C2'/></td>";
		echo "<td><input type='submit' name='subD2' value='D2'/></td>";
		echo "<td><input type='submit' name='subE2' value='E2'/></td>";
		echo "<td><input type='submit' name='subF2' value='F2'/></td>";
		echo "<td><input type='submit' name='subG2' value='G2'/></td>";
		echo "<td><input type='submit' name='subH2' value='H2'/></td>";
		echo "<td><input type='submit' name='subI2' value='I2'/></td>";
		echo "<td><input type='submit' name='subJ2' value='J2'/></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>3</th>";
		echo "<td><input type='submit' name='subA3' value='A3'/></td>";
		echo "<td><input type='submit' name='subB3' value='B3'/></td>";
		echo "<td><input type='submit' name='subC3' value='C3'/></td>";
		echo "<td><input type='submit' name='subD3' value='D3'/></td>";
		echo "<td><input type='submit' name='subE3' value='E3'/></td>";
		echo "<td><input type='submit' name='subF3' value='F3'/></td>";
		echo "<td><input type='submit' name='subG3' value='G3'/></td>";
		echo "<td><input type='submit' name='subH3' value='H3'/></td>";
		echo "<td><input type='submit' name='subI3' value='I3'/></td>";
		echo "<td><input type='submit' name='subJ3' value='J3'/></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>4</th>";
		echo "<td><input type='submit' name='subA4' value='A4'/></td>";
		echo "<td><input type='submit' name='subB4' value='B4'/></td>";
		echo "<td><input type='submit' name='subC4' value='C4'/></td>";
		echo "<td><input type='submit' name='subD4' value='D4'/></td>";
		echo "<td><input type='submit' name='subE4' value='E4'/></td>";
		echo "<td><input type='submit' name='subF4' value='F4'/></td>";
		echo "<td><input type='submit' name='subG4' value='G4'/></td>";
		echo "<td><input type='submit' name='subH4' value='H4'/></td>";
		echo "<td><input type='submit' name='subI4' value='I4'/></td>";
		echo "<td><input type='submit' name='subJ4' value='J4'/></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>5</th>";
		echo "<td><input type='submit' name='subA5' value='A5'/></td>";
		echo "<td><input type='submit' name='subB5' value='B5'/></td>";
		echo "<td><input type='submit' name='subC5' value='C5'/></td>";
		echo "<td><input type='submit' name='subD5' value='D5'/></td>";
		echo "<td><input type='submit' name='subE5' value='E5'/></td>";
		echo "<td><input type='submit' name='subF5' value='F5'/></td>";
		echo "<td><input type='submit' name='subG5' value='G5'/></td>";
		echo "<td><input type='submit' name='subH5' value='H5'/></td>";
		echo "<td><input type='submit' name='subI5' value='I5'/></td>";
		echo "<td><input type='submit' name='subJ5' value='J5'/></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>6</th>";
		echo "<td><input type='submit' name='subA6' value='A6'/></td>";
		echo "<td><input type='submit' name='subB6' value='B6'/></td>";
		echo "<td><input type='submit' name='subC6' value='C6'/></td>";
		echo "<td><input type='submit' name='subD6' value='D6'/></td>";
		echo "<td><input type='submit' name='subE6' value='E6'/></td>";
		echo "<td><input type='submit' name='subF6' value='F6'/></td>";
		echo "<td><input type='submit' name='subG6' value='G6'/></td>";
		echo "<td><input type='submit' name='subH6' value='H6'/></td>";
		echo "<td><input type='submit' name='subI6' value='I6'/></td>";
		echo "<td><input type='submit' name='subJ6' value='J6'/></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>7</th>";
		echo "<td><input type='submit' name='subA7' value='A7'/></td>";
		echo "<td><input type='submit' name='subB7' value='B7'/></td>";
		echo "<td><input type='submit' name='subC7' value='C7'/></td>";
		echo "<td><input type='submit' name='subD7' value='D7'/></td>";
		echo "<td><input type='submit' name='subE7' value='E7'/></td>";
		echo "<td><input type='submit' name='subF7' value='F7'/></td>";
		echo "<td><input type='submit' name='subG7' value='G7'/></td>";
		echo "<td><input type='submit' name='subH7' value='H7'/></td>";
		echo "<td><input type='submit' name='subI7' value='I7'/></td>";
		echo "<td><input type='submit' name='subJ7' value='J7'/></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>8</th>";
		echo "<td><input type='submit' name='subA8' value='A8'/></td>";
		echo "<td><input type='submit' name='subB8' value='B8'/></td>";
		echo "<td><input type='submit' name='subC8' value='C8'/></td>";
		echo "<td><input type='submit' name='subD8' value='D8'/></td>";
		echo "<td><input type='submit' name='subE8' value='E8'/></td>";
		echo "<td><input type='submit' name='subF8' value='F8'/></td>";
		echo "<td><input type='submit' name='subG8' value='G8'/></td>";
		echo "<td><input type='submit' name='subH8' value='H8'/></td>";
		echo "<td><input type='submit' name='subI8' value='I8'/></td>";
		echo "<td><input type='submit' name='subJ8' value='J8'/></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>9</th>";
		echo "<td><input type='submit' name='subA9' value='A9'/></td>";
		echo "<td><input type='submit' name='subB9' value='B9'/></td>";
		echo "<td><input type='submit' name='subC9' value='C9'/></td>";
		echo "<td><input type='submit' name='subD9' value='D9'/></td>";
		echo "<td><input type='submit' name='subE9' value='E9'/></td>";
		echo "<td><input type='submit' name='subF9' value='F9'/></td>";
		echo "<td><input type='submit' name='subG9' value='G9'/></td>";
		echo "<td><input type='submit' name='subH9' value='H9'/></td>";
		echo "<td><input type='submit' name='subI9' value='I9'/></td>";
		echo "<td><input type='submit' name='subJ9' value='J9'/></td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>10</th>";
		echo "<td><input type='submit' name='subA10' value='A10'/></td>";
		echo "<td><input type='submit' name='subB10' value='B10'/></td>";
		echo "<td><input type='submit' name='subC10' value='C10'/></td>";
		echo "<td><input type='submit' name='subD10' value='D10'/></td>";
		echo "<td><input type='submit' name='subE10' value='E10'/></td>";
		echo "<td><input type='submit' name='subF10' value='F10'/></td>";
		echo "<td><input type='submit' name='subG10' value='G10'/></td>";
		echo "<td><input type='submit' name='subH10' value='H10'/></td>";
		echo "<td><input type='submit' name='subI10' value='I10'/></td>";
		echo "<td><input type='submit' name='subJ10' value='J10'/></td>";
	echo "</tr>";
echo "</table>";

echo "<form metdod='post'>";	
echo "<table border=1>";
	echo "<tr>";
	echo "<th></th><th>A</th><th>B</th><th>C</th><th>D</th><th>E</th><th>F</th><th>G</th><th>H</th><th>I</th><th>J</th>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>1</th>";
		echo "<td style='margin:-20;'>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>2</th>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>3</th>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>4</th>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>5</th>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>6</th>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>7</th>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>8</th>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>9</th>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<th>10</th>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
		echo "<td>".$emptysea."</td>";
	echo "</tr>";
echo "</table>";

echo "</body>";
echo "</html>";